### ISSUE TITLE
NullPointerException occures createUpperThirdLayout() method. 

### ISSUE THREAD

**Issue by sjnaveenkumar** [DFTinc/onyx-imagery-android#1]
08-23 18:44:25.723 18417-18417/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.dft.onyx.samples.onyxdemoimagepyramiding, PID: 18417
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dft.onyx.samples.onyxdemoimagepyramiding/com.dft.onyx.samples.onyxdemoimagepyramiding.OnyxDemoImagePyramiding}: java.lang.NullPointerException
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
                                                       at android.os.Handler.dispatchMessage(Handler.java:110)
                                                       at android.os.Looper.loop(Looper.java:193)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.NullPointerException
                                                       at com.dft.onyxcamera.ui.OnyxFragment.createUpperThirdLayout(SourceFile:220)
                                                       at com.dft.onyxcamera.ui.OnyxFragment.createCameraFragmentLayout(SourceFile:184)
                                                       at com.dft.onyxcamera.ui.OnyxFragment.onCreateView(SourceFile:173)
                                                       at android.app.Fragment.performCreateView(Fragment.java:1700)
                                                       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
                                                       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
                                                       at android.app.BackStackRecord.run(BackStackRecord.java:698)
                                                       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
                                                       at android.app.Activity.performStart(Activity.java:5273)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                       at android.os.Looper.loop(Looper.java:193) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5292) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644) 
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by sjnaveenkumar** [comment]
Getting crashed on this line. 

 private LinearLayout createUpperThirdLayout() 
{
        LinearLayout var1 = new LinearLayout(this.getActivity());
        var1.setLayoutParams(new android.widget.LinearLayout.LayoutParams(-1, -1));
        var1.setOrientation(1);
        var1.setWeightSum(3.0F);
        FrameLayout var2 = (FrameLayout)this.getCameraLayoutController();
        android.widget.LinearLayout.LayoutParams var3 = new 
        android.widget.LinearLayout.LayoutParams(-1, -1, 2.0F);
        View var4 = new View(this.getActivity());
        android.widget.LinearLayout.LayoutParams var5 = new 
        android.widget.LinearLayout.LayoutParams(-1, -1, 1.0F);
        **if(var2.getParent() != null) {
            ((ViewGroup)var2.getParent()).removeView(var2);
        }**
        var1.addView(var2, var3);
        var1.addView(var4, var5);
        return var1;
    }
